/**
 * Icon shim — lucide-compatible components backed by HugeIcons.
 *
 * The whole app imports icons from here (was lucide-react). Each export is a
 * lucide-named component that renders the HugeIcons equivalent, accepting the
 * same `className` (Tailwind h-/w- sizing + text-color) usage. GENERATED by
 * scripts/gen-icons.mjs — edit the map there, not this file.
 */

import type { ReactElement, SVGProps } from 'react'

import { HugeiconsIcon } from '@hugeicons/react'
import {
  Add01Icon,
  AiBrain01Icon,
  Alert01Icon,
  AlertCircleIcon,
  AnalyticsUpIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowReloadHorizontalIcon,
  ArrowRight01Icon,
  ArrowUpRight01Icon,
  Award01Icon,
  BarChartIcon,
  BookBookmark01Icon,
  BookOpen01Icon,
  Bookmark01Icon,
  BubbleChatIcon,
  Building06Icon,
  Calculator01Icon,
  CalendarClockIcon,
  CalendarDaysIcon,
  Call02Icon,
  Cancel01Icon,
  CancelCircleIcon,
  ChampionIcon,
  CheckListIcon,
  CheckmarkCircle02Icon,
  CircleIcon,
  Clock01Icon,
  CloudUploadIcon,
  Copy01Icon,
  CreditCardIcon,
  Crown02Icon,
  DashboardSquare01Icon,
  DashboardSquare02Icon,
  Database01Icon,
  Delete02Icon,
  Download01Icon,
  Edit02Icon,
  File01Icon,
  FireIcon,
  FlashIcon,
  FloppyDiskIcon,
  GiftIcon,
  GlobalIcon,
  GridViewIcon,
  HelpCircleIcon,
  Home01Icon,
  Idea01Icon,
  InboxIcon,
  InformationCircleIcon,
  Key01Icon,
  Layers01Icon,
  LibrariesIcon,
  LifebuoyIcon,
  LinkSquare02Icon,
  Loading03Icon,
  LockIcon,
  Logout01Icon,
  MagicWand01Icon,
  Mail01Icon,
  Medal01Icon,
  Megaphone01Icon,
  Message01Icon,
  MessageAdd01Icon,
  Mortarboard01Icon,
  Notification03Icon,
  PaintBoardIcon,
  PencilEdit01Icon,
  PercentIcon,
  PieChartIcon,
  PlayCircleIcon,
  PlayIcon,
  PuzzleIcon,
  Quiz01Icon,
  RadioIcon,
  RupeeIcon,
  SecurityCheckIcon,
  SentIcon,
  Settings01Icon,
  Share08Icon,
  Shield01Icon,
  ShuffleIcon,
  SparklesIcon,
  SquareIcon,
  StarIcon,
  Sword01Icon,
  Target01Icon,
  TestTube01Icon,
  Tick02Icon,
  TickDouble01Icon,
  TranslateIcon,
  Upload01Icon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
  ViewIcon,
  ViewOffSlashIcon,
} from '@hugeicons/core-free-icons'

// Mirrors lucide-react: every SVG attribute (className, style, onClick,
// aria-*, ...) is accepted and forwarded. `strokeWidth` is narrowed to
// `number` (HugeIcons wants a number) and `size` is added (lucide extra).
export interface IconProps
  extends Omit<SVGProps<SVGSVGElement>, 'ref' | 'strokeWidth'> {
  size?: number | string
  strokeWidth?: number
}

/** Drop-in type for `icon: LucideIcon` props elsewhere in the app. */
export type LucideIcon = (props: IconProps) => ReactElement

type HugeIcon = Parameters<typeof HugeiconsIcon>[0]['icon']

function make(icon: HugeIcon): LucideIcon {
  return function Icon({ strokeWidth = 1.8, color, ...rest }: IconProps) {
    return (
      <HugeiconsIcon
        icon={icon}
        strokeWidth={strokeWidth}
        color={color ?? 'currentColor'}
        {...rest}
      />
    )
  }
}

export const AlertCircle = make(AlertCircleIcon)
export const AlertTriangle = make(Alert01Icon)
export const ArrowLeft = make(ArrowLeft01Icon)
export const ArrowRight = make(ArrowRight01Icon)
export const ArrowUpRight = make(ArrowUpRight01Icon)
export const Award = make(Award01Icon)
export const BarChart3 = make(BarChartIcon)
export const Bell = make(Notification03Icon)
export const Blocks = make(DashboardSquare02Icon)
export const BookCheck = make(BookBookmark01Icon)
export const BookOpen = make(BookOpen01Icon)
export const BookOpenCheck = make(BookOpen01Icon)
export const Bookmark = make(Bookmark01Icon)
export const Bot = make(AiBrain01Icon)
export const Building2 = make(Building06Icon)
export const Calculator = make(Calculator01Icon)
export const CalendarClock = make(CalendarClockIcon)
export const CalendarDays = make(CalendarDaysIcon)
export const Check = make(Tick02Icon)
export const CheckCheck = make(TickDouble01Icon)
export const CheckCircle2 = make(CheckmarkCircle02Icon)
export const ChevronDown = make(ArrowDown01Icon)
export const ChevronRight = make(ArrowRight01Icon)
export const Circle = make(CircleIcon)
export const ClipboardCheck = make(CheckListIcon)
export const Clock = make(Clock01Icon)
export const Copy = make(Copy01Icon)
export const CreditCard = make(CreditCardIcon)
export const Crown = make(Crown02Icon)
export const Database = make(Database01Icon)
export const Download = make(Download01Icon)
export const ExternalLink = make(LinkSquare02Icon)
export const Eye = make(ViewIcon)
export const EyeOff = make(ViewOffSlashIcon)
export const FileEdit = make(Edit02Icon)
export const FileQuestion = make(Quiz01Icon)
export const FileText = make(File01Icon)
export const Flame = make(FireIcon)
export const FlaskConical = make(TestTube01Icon)
export const Gift = make(GiftIcon)
export const Globe = make(GlobalIcon)
export const Globe2 = make(GlobalIcon)
export const GraduationCap = make(Mortarboard01Icon)
export const Grid3x3 = make(GridViewIcon)
export const HelpCircle = make(HelpCircleIcon)
export const Home = make(Home01Icon)
export const Inbox = make(InboxIcon)
export const IndianRupee = make(RupeeIcon)
export const Info = make(InformationCircleIcon)
export const KeyRound = make(Key01Icon)
export const Languages = make(TranslateIcon)
export const Layers = make(Layers01Icon)
export const LayoutDashboard = make(DashboardSquare01Icon)
export const Library = make(LibrariesIcon)
export const LifeBuoy = make(LifebuoyIcon)
export const Lightbulb = make(Idea01Icon)
export const ListChecks = make(CheckListIcon)
export const Loader2 = make(Loading03Icon)
export const Lock = make(LockIcon)
export const LogOut = make(Logout01Icon)
export const Mail = make(Mail01Icon)
export const Medal = make(Medal01Icon)
export const Megaphone = make(Megaphone01Icon)
export const MessageCircle = make(BubbleChatIcon)
export const MessageSquare = make(Message01Icon)
export const MessageSquarePlus = make(MessageAdd01Icon)
export const Palette = make(PaintBoardIcon)
export const Pencil = make(PencilEdit01Icon)
export const Percent = make(PercentIcon)
export const Phone = make(Call02Icon)
export const PieChart = make(PieChartIcon)
export const Play = make(PlayIcon)
export const PlayCircle = make(PlayCircleIcon)
export const Plus = make(Add01Icon)
export const Puzzle = make(PuzzleIcon)
export const Radio = make(RadioIcon)
export const RotateCcw = make(ArrowReloadHorizontalIcon)
export const Save = make(FloppyDiskIcon)
export const Send = make(SentIcon)
export const Settings = make(Settings01Icon)
export const Share2 = make(Share08Icon)
export const Shield = make(Shield01Icon)
export const ShieldCheck = make(SecurityCheckIcon)
export const Shuffle = make(ShuffleIcon)
export const Sparkles = make(SparklesIcon)
export const Square = make(SquareIcon)
export const Star = make(StarIcon)
export const Swords = make(Sword01Icon)
export const Target = make(Target01Icon)
export const Trash2 = make(Delete02Icon)
export const TrendingUp = make(AnalyticsUpIcon)
export const Trophy = make(ChampionIcon)
export const Upload = make(Upload01Icon)
export const UploadCloud = make(CloudUploadIcon)
export const UserPlus = make(UserAdd01Icon)
export const UserRound = make(UserCircleIcon)
export const Users = make(UserGroupIcon)
export const Wand2 = make(MagicWand01Icon)
export const X = make(Cancel01Icon)
export const XCircle = make(CancelCircleIcon)
export const Zap = make(FlashIcon)
